// Targeted by JavaCPP version 1.5.1-SNAPSHOT: DO NOT EDIT THIS FILE

package nativerl;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static nativerl.NativeRL.*;


@Namespace("nativerl") @NoOffset @Properties(inherit = nativerl.NativeRLPresets.class)
public class Continuous extends Space {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Continuous(Pointer p) { super(p); }

    public native @ByRef FloatVector low(); public native Continuous low(FloatVector setter);
    public native @ByRef FloatVector high(); public native Continuous high(FloatVector setter);
    public native @ByRef SSizeTVector shape(); public native Continuous shape(SSizeTVector setter);

    public Continuous(@Const @ByRef FloatVector low,
                   @Const @ByRef FloatVector high,
                   @Const @ByRef SSizeTVector shape) { super((Pointer)null); allocate(low, high, shape); }
    private native void allocate(@Const @ByRef FloatVector low,
                   @Const @ByRef FloatVector high,
                   @Const @ByRef SSizeTVector shape);
}
