/*
 * This file is generated by jOOQ.
 */
package ai.skymind.skynet.data.db.jooq.tables.records;


import ai.skymind.skynet.data.db.jooq.tables.Mdp;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record20;
import org.jooq.Row20;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MdpRecord extends UpdatableRecordImpl<MdpRecord> implements Record20<Integer, Integer, Integer, String, String, Boolean, Timestamp, Timestamp, String, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -1739352049;

    /**
     * Setter for <code>public.mdp.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.mdp.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.mdp.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.mdp.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.mdp.model_id</code>.
     */
    public void setModelId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.mdp.model_id</code>.
     */
    public Integer getModelId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.mdp.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.mdp.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.mdp.reward</code>.
     */
    public void setReward(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.mdp.reward</code>.
     */
    public String getReward() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.mdp.verified</code>.
     */
    public void setVerified(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.mdp.verified</code>.
     */
    public Boolean getVerified() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.mdp.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.mdp.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>public.mdp.updated_at</code>.
     */
    public void setUpdatedAt(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.mdp.updated_at</code>.
     */
    public Timestamp getUpdatedAt() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.mdp.imports</code>.
     */
    public void setImports(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.mdp.imports</code>.
     */
    public String getImports() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.mdp.variables</code>.
     */
    public void setVariables(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.mdp.variables</code>.
     */
    public String getVariables() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.mdp.reset</code>.
     */
    public void setReset(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.mdp.reset</code>.
     */
    public String getReset() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.mdp.metrics</code>.
     */
    public void setMetrics(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.mdp.metrics</code>.
     */
    public String getMetrics() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.mdp.observation_space_size</code>.
     */
    public void setObservationSpaceSize(Integer value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.mdp.observation_space_size</code>.
     */
    public Integer getObservationSpaceSize() {
        return (Integer) get(12);
    }

    /**
     * Setter for <code>public.mdp.action_space_size</code>.
     */
    public void setActionSpaceSize(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.mdp.action_space_size</code>.
     */
    public Integer getActionSpaceSize() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>public.mdp.epochs</code>.
     */
    public void setEpochs(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.mdp.epochs</code>.
     */
    public Integer getEpochs() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.mdp.simulation_steps_length</code>.
     */
    public void setSimulationStepsLength(Integer value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.mdp.simulation_steps_length</code>.
     */
    public Integer getSimulationStepsLength() {
        return (Integer) get(15);
    }

    /**
     * Setter for <code>public.mdp.batch_size</code>.
     */
    public void setBatchSize(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.mdp.batch_size</code>.
     */
    public Integer getBatchSize() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>public.mdp.experience_replay_steps</code>.
     */
    public void setExperienceReplaySteps(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.mdp.experience_replay_steps</code>.
     */
    public Integer getExperienceReplaySteps() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>public.mdp.steps_per_update</code>.
     */
    public void setStepsPerUpdate(Integer value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.mdp.steps_per_update</code>.
     */
    public Integer getStepsPerUpdate() {
        return (Integer) get(18);
    }

    /**
     * Setter for <code>public.mdp.warmup_steps</code>.
     */
    public void setWarmupSteps(Integer value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.mdp.warmup_steps</code>.
     */
    public Integer getWarmupSteps() {
        return (Integer) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record20 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Integer, Integer, Integer, String, String, Boolean, Timestamp, Timestamp, String, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row20) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row20<Integer, Integer, Integer, String, String, Boolean, Timestamp, Timestamp, String, String, String, String, Integer, Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row20) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Mdp.MDP.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Mdp.MDP.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Mdp.MDP.MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Mdp.MDP.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Mdp.MDP.REWARD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field6() {
        return Mdp.MDP.VERIFIED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Mdp.MDP.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Mdp.MDP.UPDATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Mdp.MDP.IMPORTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Mdp.MDP.VARIABLES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Mdp.MDP.RESET;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Mdp.MDP.METRICS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field13() {
        return Mdp.MDP.OBSERVATION_SPACE_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return Mdp.MDP.ACTION_SPACE_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field15() {
        return Mdp.MDP.EPOCHS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field16() {
        return Mdp.MDP.SIMULATION_STEPS_LENGTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return Mdp.MDP.BATCH_SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field18() {
        return Mdp.MDP.EXPERIENCE_REPLAY_STEPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field19() {
        return Mdp.MDP.STEPS_PER_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field20() {
        return Mdp.MDP.WARMUP_STEPS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getReward();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component6() {
        return getVerified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getImports();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getVariables();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getReset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getMetrics();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component13() {
        return getObservationSpaceSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getActionSpaceSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component15() {
        return getEpochs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component16() {
        return getSimulationStepsLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component17() {
        return getBatchSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component18() {
        return getExperienceReplaySteps();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component19() {
        return getStepsPerUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component20() {
        return getWarmupSteps();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getReward();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value6() {
        return getVerified();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getImports();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getVariables();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getReset();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getMetrics();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value13() {
        return getObservationSpaceSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getActionSpaceSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value15() {
        return getEpochs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value16() {
        return getSimulationStepsLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getBatchSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value18() {
        return getExperienceReplaySteps();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value19() {
        return getStepsPerUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value20() {
        return getWarmupSteps();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value3(Integer value) {
        setModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value5(String value) {
        setReward(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value6(Boolean value) {
        setVerified(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value7(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value8(Timestamp value) {
        setUpdatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value9(String value) {
        setImports(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value10(String value) {
        setVariables(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value11(String value) {
        setReset(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value12(String value) {
        setMetrics(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value13(Integer value) {
        setObservationSpaceSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value14(Integer value) {
        setActionSpaceSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value15(Integer value) {
        setEpochs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value16(Integer value) {
        setSimulationStepsLength(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value17(Integer value) {
        setBatchSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value18(Integer value) {
        setExperienceReplaySteps(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value19(Integer value) {
        setStepsPerUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord value20(Integer value) {
        setWarmupSteps(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MdpRecord values(Integer value1, Integer value2, Integer value3, String value4, String value5, Boolean value6, Timestamp value7, Timestamp value8, String value9, String value10, String value11, String value12, Integer value13, Integer value14, Integer value15, Integer value16, Integer value17, Integer value18, Integer value19, Integer value20) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MdpRecord
     */
    public MdpRecord() {
        super(Mdp.MDP);
    }

    /**
     * Create a detached, initialised MdpRecord
     */
    public MdpRecord(Integer id, Integer userId, Integer modelId, String name, String reward, Boolean verified, Timestamp createdAt, Timestamp updatedAt, String imports, String variables, String reset, String metrics, Integer observationSpaceSize, Integer actionSpaceSize, Integer epochs, Integer simulationStepsLength, Integer batchSize, Integer experienceReplaySteps, Integer stepsPerUpdate, Integer warmupSteps) {
        super(Mdp.MDP);

        set(0, id);
        set(1, userId);
        set(2, modelId);
        set(3, name);
        set(4, reward);
        set(5, verified);
        set(6, createdAt);
        set(7, updatedAt);
        set(8, imports);
        set(9, variables);
        set(10, reset);
        set(11, metrics);
        set(12, observationSpaceSize);
        set(13, actionSpaceSize);
        set(14, epochs);
        set(15, simulationStepsLength);
        set(16, batchSize);
        set(17, experienceReplaySteps);
        set(18, stepsPerUpdate);
        set(19, warmupSteps);
    }
}
