server:
  port: 8080
spring:
  servlet:
    multipart:
      # This is a workaround for https://github.com/vaadin/spring/issues/381
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DATABASE_URL}
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

skymind:
  rescale:
    platform:
      region: platform.rescale.jp
      key: 0d0601925a547db44d41007e3cc4386b075c761c
