/*
 * This file is generated by jOOQ.
 */
package ai.skymind.skynet.data.db.jooq;


import ai.skymind.skynet.data.db.jooq.tables.Databasechangeloglock;
import ai.skymind.skynet.data.db.jooq.tables.Mdp;
import ai.skymind.skynet.data.db.jooq.tables.Model;
import ai.skymind.skynet.data.db.jooq.tables.Policy;
import ai.skymind.skynet.data.db.jooq.tables.Project;
import ai.skymind.skynet.data.db.jooq.tables.Run;
import ai.skymind.skynet.data.db.jooq.tables.User;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index DATABASECHANGELOGLOCK_PKEY = Indexes0.DATABASECHANGELOGLOCK_PKEY;
    public static final Index MDP_PKEY = Indexes0.MDP_PKEY;
    public static final Index MODEL_PKEY = Indexes0.MODEL_PKEY;
    public static final Index POLICY_PKEY = Indexes0.POLICY_PKEY;
    public static final Index PROJECT_PKEY = Indexes0.PROJECT_PKEY;
    public static final Index RUN_PKEY = Indexes0.RUN_PKEY;
    public static final Index USER_PKEY = Indexes0.USER_PKEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index DATABASECHANGELOGLOCK_PKEY = Internal.createIndex("databasechangeloglock_pkey", Databasechangeloglock.DATABASECHANGELOGLOCK, new OrderField[] { Databasechangeloglock.DATABASECHANGELOGLOCK.ID }, true);
        public static Index MDP_PKEY = Internal.createIndex("mdp_pkey", Mdp.MDP, new OrderField[] { Mdp.MDP.ID }, true);
        public static Index MODEL_PKEY = Internal.createIndex("model_pkey", Model.MODEL, new OrderField[] { Model.MODEL.ID }, true);
        public static Index POLICY_PKEY = Internal.createIndex("policy_pkey", Policy.POLICY, new OrderField[] { Policy.POLICY.ID }, true);
        public static Index PROJECT_PKEY = Internal.createIndex("project_pkey", Project.PROJECT, new OrderField[] { Project.PROJECT.ID }, true);
        public static Index RUN_PKEY = Internal.createIndex("run_pkey", Run.RUN, new OrderField[] { Run.RUN.ID }, true);
        public static Index USER_PKEY = Internal.createIndex("user_pkey", User.USER, new OrderField[] { User.USER.ID }, true);
    }
}
