/*
 * This file is generated by jOOQ.
 */
package ai.skymind.skynet.data.db.jooq.tables.records;


import ai.skymind.skynet.data.db.jooq.tables.Policy;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PolicyRecord extends UpdatableRecordImpl<PolicyRecord> implements Record7<Integer, Integer, Integer, Integer, Integer, Timestamp, String> {

    private static final long serialVersionUID = 1880610936;

    /**
     * Setter for <code>public.policy.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.policy.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.policy.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.policy.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.policy.model_id</code>.
     */
    public void setModelId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.policy.model_id</code>.
     */
    public Integer getModelId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.policy.mdp_id</code>.
     */
    public void setMdpId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.policy.mdp_id</code>.
     */
    public Integer getMdpId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.policy.run_id</code>.
     */
    public void setRunId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.policy.run_id</code>.
     */
    public Integer getRunId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.policy.created_at</code>.
     */
    public void setCreatedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.policy.created_at</code>.
     */
    public Timestamp getCreatedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.policy.file_id</code>. This is the file id as returned by rescale api
     */
    public void setFileId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.policy.file_id</code>. This is the file id as returned by rescale api
     */
    public String getFileId() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Policy.POLICY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Policy.POLICY.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Policy.POLICY.MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Policy.POLICY.MDP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Policy.POLICY.RUN_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Policy.POLICY.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Policy.POLICY.FILE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getMdpId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getRunId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getMdpId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getRunId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFileId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value3(Integer value) {
        setModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value4(Integer value) {
        setMdpId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value5(Integer value) {
        setRunId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value6(Timestamp value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value7(String value) {
        setFileId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PolicyRecord
     */
    public PolicyRecord() {
        super(Policy.POLICY);
    }

    /**
     * Create a detached, initialised PolicyRecord
     */
    public PolicyRecord(Integer id, Integer userId, Integer modelId, Integer mdpId, Integer runId, Timestamp createdAt, String fileId) {
        super(Policy.POLICY);

        set(0, id);
        set(1, userId);
        set(2, modelId);
        set(3, mdpId);
        set(4, runId);
        set(5, createdAt);
        set(6, fileId);
    }
}
