/*
 * This file is generated by jOOQ.
 */
package ai.skymind.skynet.data.db.jooq.tables.records;


import ai.skymind.skynet.data.db.jooq.tables.Policy;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PolicyRecord extends UpdatableRecordImpl<PolicyRecord> implements Record7<Integer, Integer, Integer, Integer, Integer, Timestamp, String> {

    private static final long serialVersionUID = -35490174;

    /**
     * Setter for <code>public.policy.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.policy.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.policy.userId</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.policy.userId</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.policy.modelId</code>.
     */
    public void setModelid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.policy.modelId</code>.
     */
    public Integer getModelid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.policy.mdpId</code>.
     */
    public void setMdpid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.policy.mdpId</code>.
     */
    public Integer getMdpid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.policy.runId</code>.
     */
    public void setRunid(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.policy.runId</code>.
     */
    public Integer getRunid() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.policy.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.policy.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.policy.fileId</code>. This is the file id as returned by rescale api
     */
    public void setFileid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.policy.fileId</code>. This is the file id as returned by rescale api
     */
    public String getFileid() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Policy.POLICY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Policy.POLICY.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Policy.POLICY.MODELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Policy.POLICY.MDPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Policy.POLICY.RUNID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Policy.POLICY.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Policy.POLICY.FILEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getModelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getMdpid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getRunid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getFileid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getModelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getMdpid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getRunid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getFileid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value3(Integer value) {
        setModelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value4(Integer value) {
        setMdpid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value5(Integer value) {
        setRunid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value6(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord value7(String value) {
        setFileid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PolicyRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PolicyRecord
     */
    public PolicyRecord() {
        super(Policy.POLICY);
    }

    /**
     * Create a detached, initialised PolicyRecord
     */
    public PolicyRecord(Integer id, Integer userid, Integer modelid, Integer mdpid, Integer runid, Timestamp createdat, String fileid) {
        super(Policy.POLICY);

        set(0, id);
        set(1, userid);
        set(2, modelid);
        set(3, mdpid);
        set(4, runid);
        set(5, createdat);
        set(6, fileid);
    }
}
