/*
 * This file is generated by jOOQ.
 */
package ai.skymind.skynet.data.db.jooq.tables.records;


import ai.skymind.skynet.data.db.jooq.tables.Run;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RunRecord extends UpdatableRecordImpl<RunRecord> implements Record7<Integer, Integer, Integer, Integer, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = 1269471342;

    /**
     * Setter for <code>public.run.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.run.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.run.user_id</code>.
     */
    public void setUserId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.run.user_id</code>.
     */
    public Integer getUserId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.run.model_id</code>.
     */
    public void setModelId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.run.model_id</code>.
     */
    public Integer getModelId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.run.mdp_id</code>.
     */
    public void setMdpId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.run.mdp_id</code>.
     */
    public Integer getMdpId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.run.started_at</code>.
     */
    public void setStartedAt(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.run.started_at</code>.
     */
    public Timestamp getStartedAt() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.run.finished_at</code>.
     */
    public void setFinishedAt(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.run.finished_at</code>.
     */
    public Timestamp getFinishedAt() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.run.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.run.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Timestamp, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Timestamp, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Run.RUN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Run.RUN.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Run.RUN.MODEL_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Run.RUN.MDP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Run.RUN.STARTED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Run.RUN.FINISHED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Run.RUN.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getMdpId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getStartedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getFinishedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getModelId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getMdpId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getStartedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getFinishedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value2(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value3(Integer value) {
        setModelId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value4(Integer value) {
        setMdpId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value5(Timestamp value) {
        setStartedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value6(Timestamp value) {
        setFinishedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value7(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RunRecord
     */
    public RunRecord() {
        super(Run.RUN);
    }

    /**
     * Create a detached, initialised RunRecord
     */
    public RunRecord(Integer id, Integer userId, Integer modelId, Integer mdpId, Timestamp startedAt, Timestamp finishedAt, String status) {
        super(Run.RUN);

        set(0, id);
        set(1, userId);
        set(2, modelId);
        set(3, mdpId);
        set(4, startedAt);
        set(5, finishedAt);
        set(6, status);
    }
}
