/*
 * This file is generated by jOOQ.
 */
package ai.skymind.skynet.data.db.jooq.tables.records;


import ai.skymind.skynet.data.db.jooq.tables.Run;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RunRecord extends UpdatableRecordImpl<RunRecord> implements Record7<Integer, Integer, Integer, Integer, Timestamp, Timestamp, String> {

    private static final long serialVersionUID = -1773329707;

    /**
     * Setter for <code>public.run.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.run.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.run.userId</code>.
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.run.userId</code>.
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.run.modelId</code>.
     */
    public void setModelid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.run.modelId</code>.
     */
    public Integer getModelid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.run.mdpId</code>.
     */
    public void setMdpid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.run.mdpId</code>.
     */
    public Integer getMdpid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.run.startedAt</code>.
     */
    public void setStartedat(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.run.startedAt</code>.
     */
    public Timestamp getStartedat() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.run.finishedAt</code>.
     */
    public void setFinishedat(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.run.finishedAt</code>.
     */
    public Timestamp getFinishedat() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.run.status</code>.
     */
    public void setStatus(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.run.status</code>.
     */
    public String getStatus() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Timestamp, Timestamp, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Timestamp, Timestamp, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Run.RUN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Run.RUN.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Run.RUN.MODELID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Run.RUN.MDPID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Run.RUN.STARTEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Run.RUN.FINISHEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Run.RUN.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getModelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getMdpid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getStartedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getFinishedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getModelid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getMdpid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getStartedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getFinishedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value3(Integer value) {
        setModelid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value4(Integer value) {
        setMdpid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value5(Timestamp value) {
        setStartedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value6(Timestamp value) {
        setFinishedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord value7(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public RunRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RunRecord
     */
    public RunRecord() {
        super(Run.RUN);
    }

    /**
     * Create a detached, initialised RunRecord
     */
    public RunRecord(Integer id, Integer userid, Integer modelid, Integer mdpid, Timestamp startedat, Timestamp finishedat, String status) {
        super(Run.RUN);

        set(0, id);
        set(1, userid);
        set(2, modelid);
        set(3, mdpid);
        set(4, startedat);
        set(5, finishedat);
        set(6, status);
    }
}
