/*
 * This file is generated by jOOQ.
 */
package ai.skymind.skynet.data.db.jooq;


import javax.annotation.Generated;

import org.jooq.Sequence;
import org.jooq.impl.SequenceImpl;


/**
 * Convenience access to all sequences in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sequences {

    /**
     * The sequence <code>public.mdp_id_seq</code>
     */
    public static final Sequence<Integer> MDP_ID_SEQ = new SequenceImpl<Integer>("mdp_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.model_id_seq</code>
     */
    public static final Sequence<Integer> MODEL_ID_SEQ = new SequenceImpl<Integer>("model_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.policy_id_seq</code>
     */
    public static final Sequence<Integer> POLICY_ID_SEQ = new SequenceImpl<Integer>("policy_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.project_id_seq</code>
     */
    public static final Sequence<Integer> PROJECT_ID_SEQ = new SequenceImpl<Integer>("project_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.run_id_seq</code>
     */
    public static final Sequence<Integer> RUN_ID_SEQ = new SequenceImpl<Integer>("run_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));

    /**
     * The sequence <code>public.user_id_seq</code>
     */
    public static final Sequence<Integer> USER_ID_SEQ = new SequenceImpl<Integer>("user_id_seq", Public.PUBLIC, org.jooq.impl.SQLDataType.INTEGER.nullable(false));
}
