/*
 * This file is generated by jOOQ.
 */
package ai.skymind.skynet.data.db.jooq;


import ai.skymind.skynet.data.db.jooq.tables.Databasechangelog;
import ai.skymind.skynet.data.db.jooq.tables.Databasechangeloglock;
import ai.skymind.skynet.data.db.jooq.tables.Mdp;
import ai.skymind.skynet.data.db.jooq.tables.Model;
import ai.skymind.skynet.data.db.jooq.tables.Policy;
import ai.skymind.skynet.data.db.jooq.tables.Project;
import ai.skymind.skynet.data.db.jooq.tables.Run;
import ai.skymind.skynet.data.db.jooq.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.databasechangelog</code>.
     */
    public static final Databasechangelog DATABASECHANGELOG = ai.skymind.skynet.data.db.jooq.tables.Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>public.databasechangeloglock</code>.
     */
    public static final Databasechangeloglock DATABASECHANGELOGLOCK = ai.skymind.skynet.data.db.jooq.tables.Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>public.mdp</code>.
     */
    public static final Mdp MDP = ai.skymind.skynet.data.db.jooq.tables.Mdp.MDP;

    /**
     * The table <code>public.model</code>.
     */
    public static final Model MODEL = ai.skymind.skynet.data.db.jooq.tables.Model.MODEL;

    /**
     * The table <code>public.policy</code>.
     */
    public static final Policy POLICY = ai.skymind.skynet.data.db.jooq.tables.Policy.POLICY;

    /**
     * The table <code>public.project</code>.
     */
    public static final Project PROJECT = ai.skymind.skynet.data.db.jooq.tables.Project.PROJECT;

    /**
     * The table <code>public.run</code>.
     */
    public static final Run RUN = ai.skymind.skynet.data.db.jooq.tables.Run.RUN;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = ai.skymind.skynet.data.db.jooq.tables.User.USER;
}
