/*
 * This file is generated by jOOQ.
 */
package ai.skymind.skynet.data.db.jooq.tables;


import ai.skymind.skynet.data.db.jooq.Indexes;
import ai.skymind.skynet.data.db.jooq.Keys;
import ai.skymind.skynet.data.db.jooq.Public;
import ai.skymind.skynet.data.db.jooq.tables.records.RunRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Run extends TableImpl<RunRecord> {

    private static final long serialVersionUID = -768539067;

    /**
     * The reference instance of <code>public.run</code>
     */
    public static final Run RUN = new Run();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RunRecord> getRecordType() {
        return RunRecord.class;
    }

    /**
     * The column <code>public.run.id</code>.
     */
    public final TableField<RunRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('run_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.run.userId</code>.
     */
    public final TableField<RunRecord, Integer> USERID = createField("userId", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.run.modelId</code>.
     */
    public final TableField<RunRecord, Integer> MODELID = createField("modelId", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.run.mdpId</code>.
     */
    public final TableField<RunRecord, Integer> MDPID = createField("mdpId", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.run.startedAt</code>.
     */
    public final TableField<RunRecord, Timestamp> STARTEDAT = createField("startedAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.run.finishedAt</code>.
     */
    public final TableField<RunRecord, Timestamp> FINISHEDAT = createField("finishedAt", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.run.status</code>.
     */
    public final TableField<RunRecord, String> STATUS = createField("status", org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.run</code> table reference
     */
    public Run() {
        this(DSL.name("run"), null);
    }

    /**
     * Create an aliased <code>public.run</code> table reference
     */
    public Run(String alias) {
        this(DSL.name(alias), RUN);
    }

    /**
     * Create an aliased <code>public.run</code> table reference
     */
    public Run(Name alias) {
        this(alias, RUN);
    }

    private Run(Name alias, Table<RunRecord> aliased) {
        this(alias, aliased, null);
    }

    private Run(Name alias, Table<RunRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Run(Table<O> child, ForeignKey<O, RunRecord> key) {
        super(child, key, RUN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.RUN_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<RunRecord, Integer> getIdentity() {
        return Keys.IDENTITY_RUN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<RunRecord> getPrimaryKey() {
        return Keys.RUN_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<RunRecord>> getKeys() {
        return Arrays.<UniqueKey<RunRecord>>asList(Keys.RUN_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<RunRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<RunRecord, ?>>asList(Keys.RUN__RUN_OWNER, Keys.RUN__RUN_MODEL, Keys.RUN__RUN_MDP);
    }

    public User user() {
        return new User(this, Keys.RUN__RUN_OWNER);
    }

    public Model model() {
        return new Model(this, Keys.RUN__RUN_MODEL);
    }

    public Mdp mdp() {
        return new Mdp(this, Keys.RUN__RUN_MDP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Run as(String alias) {
        return new Run(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Run as(Name alias) {
        return new Run(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Run rename(String name) {
        return new Run(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Run rename(Name name) {
        return new Run(name, null);
    }
}
