set -eo pipefail ;
aws s3 cp s3://${ENVIRONMENT}-training-static-files.pathmind.com/jdk/8_222/OpenJDK8U-jdk_x64_linux_hotspot_8u222b10.tar.gz OpenJDK8U-jdk_x64_linux_hotspot_8u222b10.tar.gz > /dev/null ;
aws s3 cp s3://${ENVIRONMENT}-training-static-files.pathmind.com/conda/0_7_6/rllibpack.tar.gz rllibpack.tar.gz > /dev/null ;
aws s3 cp s3://${ENVIRONMENT}-training-static-files.pathmind.com/nativerl/pr_test/nativerl-1.0.0-SNAPSHOT-bin.zip nativerl-1.0.0-SNAPSHOT-bin.zip > /dev/null ;
aws s3 cp s3://${ENVIRONMENT}-training-static-files.pathmind.com/anylogic/8_5_2/baseEnv.zip baseEnv.zip > /dev/null ;
aws s3 cp s3://${ENVIRONMENT}-training-static-files.pathmind.com/pathmindhelper/1_0_1/PathmindPolicy.jar PathmindPolicy.jar > /dev/null ;
aws s3 cp s3://dev-training-dynamic-files.pathmind.com/model_file/11543 model.zip > /dev/null ;
tar xf OpenJDK8U-jdk_x64_linux_hotspot_8u222b10.tar.gz > /dev/null ;
rm -rf OpenJDK8U-jdk_x64_linux_hotspot_8u222b10.tar.gz ;
export JAVA_HOME=`pwd`/jdk8u222-b10 ;
export JDK_HOME=$JAVA_HOME ;
export JRE_HOME=$JAVA_HOME/jre ;
export PATH=$JAVA_HOME/bin:$PATH ;
export LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server:$JAVA_HOME/jre/lib/amd64/:$LD_LIBRARY_PATH ;
mkdir -p conda ;
cd conda ;
tar xf ../rllibpack.tar.gz > /dev/null ;
rm ../rllibpack.tar.gz ;
source bin/activate ;
cd .. ;
mkdir -p work ;
cd work ;
unzip ../nativerl-1.0.0-SNAPSHOT-bin.zip > /dev/null ;
rm ../nativerl-1.0.0-SNAPSHOT-bin.zip ;
mv nativerl-bin/* . ;
mv examples/train.sh . ;
cd .. ;
unzip baseEnv.zip > /dev/null ;
rm baseEnv.zip ;
mv baseEnv/* work/ ;
rm -r baseEnv ;
mv PathmindPolicy.jar work/lib/ ;
cd work ;
unzip ../model.zip > /dev/null ;
rm ../model.zip ;
export CLASS_SNIPPET='' ;
export RESET_SNIPPET='' ;
export REWARD_SNIPPET='reward += after[0] - before[0];' ;
export METRICS_SNIPPET='' ;
export DISCRETE_ACTIONS='4' ;
export CONTINUOUS_OBSERVATIONS='5' ;
export MAX_ITERATIONS='250' ;
export TEST_ITERATIONS='0' ;
export STEP_TIME='1' ;
export STOP_TIME='420' ;
export TIME_UNIT='MINUTE' ;
export MAX_TIME_IN_SEC='43200' ;
export NUM_SAMPLES='4' ;
export MULTIAGENT='false' ;
export RESUME=${RESUME:='false'} ;
export CHECKPOINT_FREQUENCY='50' ;
export EPISODE_REWARD_RANGE='0.03' ;
export ENTROPY_SLOPE='0.01' ;
export VF_LOSS_RANGE='0.1' ;
export VALUE_PRED='1' ;
export USER_LOG='false' ;
echo > setup.sh ;
mkdir -p database ;
touch database/db.properties ;
source train.sh ;
exit $?
