// Targeted by JavaCPP version 1.5.1-SNAPSHOT: DO NOT EDIT THIS FILE

package ai.skymind.nativerl;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static ai.skymind.nativerl.NativeRL.*;


@Namespace("nativerl") @NoOffset @Properties(inherit = ai.skymind.nativerl.NativeRLPresets.class)
public class Discrete extends Space {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Discrete(Pointer p) { super(p); }

    public native @Cast("ssize_t") long n(); public native Discrete n(long setter);

    public Discrete(@Const @ByRef Discrete d) { super((Pointer)null); allocate(d); }
    private native void allocate(@Const @ByRef Discrete d);
    public Discrete(@Cast("ssize_t") long n) { super((Pointer)null); allocate(n); }
    private native void allocate(@Cast("ssize_t") long n);
}
