// Targeted by JavaCPP version 1.5.4: DO NOT EDIT THIS FILE

package ai.skymind.nativerl;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static ai.skymind.nativerl.NativeRL.*;


/**
 * Describes a discrete space for action spaces.
 * Includes the number of actions supported by the Environment.
 */
@Namespace("nativerl") @NoOffset @Properties(inherit = ai.skymind.nativerl.NativeRLPresets.class)
public class Discrete extends Space {
    static { Loader.load(); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Discrete(Pointer p) { super(p); }

    public native @Cast("ssize_t") long n(); public native Discrete n(long setter);
    public native @Cast("ssize_t") long size(); public native Discrete size(long setter);

    public Discrete(@Const @ByRef Discrete d) { super((Pointer)null); allocate(d); }
    private native void allocate(@Const @ByRef Discrete d);
    public Discrete(@Cast("ssize_t") long n, @Cast("ssize_t") long size/*=1*/) { super((Pointer)null); allocate(n, size); }
    private native void allocate(@Cast("ssize_t") long n, @Cast("ssize_t") long size/*=1*/);
    public Discrete(@Cast("ssize_t") long n) { super((Pointer)null); allocate(n); }
    private native void allocate(@Cast("ssize_t") long n);
}
