// Targeted by JavaCPP version 1.5.1: DO NOT EDIT THIS FILE

package ai.skymind.nativerl;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class NativeRL extends ai.skymind.nativerl.NativeRLPresets {
    static { Loader.load(); }

// Targeting FloatVector.java


// Targeting SSizeTVector.java


// Parsed from nativerl.h

// #ifndef NATIVERL_H
// #define NATIVERL_H

// #include <vector>
// Targeting Array.java


// Targeting Space.java


// Targeting Continuous.java


// Targeting Discrete.java





// Targeting Environment.java



// typedef Environment* (*CreateEnvironment)(const char* name);
// typedef void (*ReleaseEnvironment)(Environment* environment);



// #endif // NATIVERL_H


}
