// Targeted by JavaCPP version 1.5.3: DO NOT EDIT THIS FILE

package ai.skymind.nativerl;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

public class NativeRL extends ai.skymind.nativerl.NativeRLPresets {
    static { Loader.load(); }

// Targeting FloatVector.java


// Targeting SSizeTVector.java


// Parsed from nativerl.h

// #ifndef NATIVERL_H
// #define NATIVERL_H

// #include <vector>

/**
 * This is the main C++ interface implemented, for example, in Java via JavaCPP,
 * and used in Python by, for example, RLlib via pybind11.
 */
// Targeting Array.java


// Targeting Space.java


// Targeting Continuous.java


// Targeting Discrete.java



/** Helper method to cast dynamically a Space object into Continuous. */

/** Helper method to cast dynamically a Space object into Discrete. */

// Targeting Environment.java



@Namespace("nativerl") public static native @SharedPtr Environment createEnvironment(@Cast("const char*") BytePointer name);
@Namespace("nativerl") public static native @SharedPtr Environment createEnvironment(String name);



// #endif // NATIVERL_H


}
