// Targeted by JavaCPP version 1.5.1: DO NOT EDIT THIS FILE

package ai.skymind.nativerl;

import java.nio.*;
import org.bytedeco.javacpp.*;
import org.bytedeco.javacpp.annotation.*;

import static ai.skymind.nativerl.NativeRL.*;


@Namespace("nativerl") @Properties(inherit = ai.skymind.nativerl.NativeRLPresets.class)
public class Space extends Pointer {
    static { Loader.load(); }
    /** Default native constructor. */
    public Space() { super((Pointer)null); allocate(); }
    /** Native array allocator. Access with {@link Pointer#position(long)}. */
    public Space(long size) { super((Pointer)null); allocateArray(size); }
    /** Pointer cast constructor. Invokes {@link Pointer#Pointer(Pointer)}. */
    public Space(Pointer p) { super(p); }
    private native void allocate();
    private native void allocateArray(long size);
    @Override public Space position(long position) {
        return (Space)super.position(position);
    }

    public native Continuous asContinuous();
    public native Discrete asDiscrete();
}
