io:
  skymind:
    pathmind:
      model-analyzer:
        swagger:
          title: Pathmind model analyzer
          description: A service that processes an AnyLogic model to extract data needed to be used in Pathmind Platform
          base-package: io.skymind.pathmind.analyzer
spring:
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
